		{ "color0",		STRING,	&normbordercolor },
		{ "color5",		STRING,	&selbordercolor },
		{ "color0",		STRING,	&normbgcolor },
		{ "color2",		STRING,	&normfgcolor },
		{ "color0",		STRING,	&selfgcolor },
		{ "color2",		STRING,	&selbgcolor },
