		{ "color0",		STRING,	&normbordercolor },
		{ "color9",		STRING,	&selbordercolor },
		{ "color0",		STRING,	&normbgcolor },
		{ "color14",		STRING,	&normfgcolor },
		{ "color0",		STRING,	&selfgcolor },
		{ "color14",		STRING,	&selbgcolor },
