		{ "color0",		STRING,	&normbordercolor },
		{ "color8",		STRING,	&selbordercolor },
		{ "color0",		STRING,	&normbgcolor },
		{ "color15",		STRING,	&normfgcolor },
		{ "color0",		STRING,	&selfgcolor },
		{ "color15",		STRING,	&selbgcolor },
