		{ "color0",             STRING,  &normbgcolor },
		{ "color7",             STRING,  &normfgcolor },
		{ "color8",             STRING,  &normbordercolor },
		{ "color2",             STRING,  &selbgcolor },
		{ "color7",             STRING,  &selfgcolor },
		{ "color0",             STRING,  &selbordercolor },
