		{ "color0",		STRING,	&normbordercolor },
		{ "color13",		STRING,	&selbordercolor },
		{ "color0",		STRING,	&normbgcolor },
		{ "color10",		STRING,	&normfgcolor },
		{ "color0",		STRING,	&selfgcolor },
		{ "color10",		STRING,	&selbgcolor },
